"""Builds docs/PHASE2_RESULTS_TABLES.md from artifacts/phase2/*.csv (no numbers typed by hand)."""
import sys, json
from pathlib import Path
sys.path.insert(0, str(Path(__file__).resolve().parents[1]))
import pandas as pd
from kestrel import config as C
O = C.ART / "phase2"

def md(df, nd=3):
    df = df.copy()
    for c in df.columns:
        if df[c].dtype.kind == "f": df[c] = df[c].round(nd)
    h = "| " + " | ".join(map(str, df.columns)) + " |\n|" + "---|" * len(df.columns) + "\n"
    return h + "\n".join("| " + " | ".join("" if pd.isna(v) else str(v) for v in r) + " |" for r in df.itertuples(index=False)) + "\n"

cmp = pd.read_csv(O / "model_comparison_by_fold.csv"); b = pd.read_csv(O / "bootstrap_ci.csv")
sel = json.load(open(O / "model_selection.json")); out = ["# Phase 2 results tables (auto-generated by scripts/make_phase2_report.py)\n"]
for f, title in [("B_test_like", "HEADLINE: fold B (May-Jun 2026, history frozen 17 Apr, K=80)"), ("C_june", "Fold C (June 2026, K=40 = one month of capacity)"), ("A_pre_regime", "Fold A (Feb-Apr 2026, old regime, K=120) - sanity + hyper-parameter selection")]:
    x = cmp[cmp.fold == f][["model", "n_fraud", "prevalence", "pr_auc", "pr_lift", "roc_auc", "k_tp", "k_precision", "k_recall", "k_stopped_per_check", "k_net_per_check", "k_accuracy", "accuracy_all_negative", "aa_pr_auc"]]
    out += [f"\n## {title}\n", md(x)]
    out += ["\nCluster-bootstrap 95% CI (1000 reps, resampling partners):\n", md(b[(b.fold == f) & b.metric.isin(["pr_auc", "k_precision", "k_stopped_per_check", "k_net_per_check"])][["model", "metric", "mean", "lo", "hi", "diff_vs_baseline", "diff_lo", "diff_hi", "p_better"]], 3)]
out += ["\n## Top-K economics, final model (rupees; goodwill Rs 380 per genuine claim held)\n", md(pd.read_csv(O / "topk_economics.csv"), 1)]
out += ["\n## Operational threshold rule (check iff expected value > 0), separate from ranking\n", md(pd.read_csv(O / "ev_threshold_rule.csv"), 2)]
out += ["\n## Feature-group ablation: delta PR-AUC vs base (per family)\n", md(pd.read_csv(O / "ablation_delta_vs_base.csv"))]
out += ["\n## Feature decisions\n", md(pd.DataFrame(sel["feature_decisions"]).T.reset_index().rename(columns={"index": "group"}))]
out += ["\n## Hyper-parameter grid (all folds; selection used fold A only)\n", md(pd.read_csv(O / "grid_all_folds.csv").pivot(index="model", columns="fold", values="pr_auc").reset_index())]
out += ["\n## Recency weighting of post-May rows (fold C only; exploratory)\n", md(pd.read_csv(O / "regime_weighting_foldC.csv")), md(pd.read_csv(O / "regime_weighting_foldC_halves.csv"))]
out += ["\n## Diagnostics: where is the fraud relative to what the history knows?\n", md(pd.read_csv(O / "diagnostic_unseen_fraud_partners.csv")), md(pd.read_csv(O / "diagnostic_horizon_halves.csv"))]
Path(C.ROOT / "docs" / "PHASE2_RESULTS_TABLES.md").write_text("\n".join(out))
print("written")
